name: Simple Docker Downloader
on:
  workflow_dispatch:
    inputs:
      image:
        description: '镜像全名'
        required: true
        default: 'ghcr.io/home-assistant-libs/python-matter-server:stable'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image
        run: docker pull ${{ github.event.inputs.image }}
      - name: Save Image
        run: docker save ${{ github.event.inputs.image }} -o matter-server.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: matter-server-file
          path: matter-server.tar
